# ------------------------------------------------------------------------------
# --# DEFAULTS #----------------------------------------------------------------

# --- keybinds -----------------------------------------------------------------

# vim keyboard shortcuts
set -g mode-keys vi

# Set leader key to Ctrl+Space
set-option -g prefix C-Space
bind C-Space send-prefix

# unbind defaults
unbind '"'
unbind %
unbind $
unbind ,


# --- behaviour ----------------------------------------------------------------

# start index at 1
set -g base-index 1
set -g pane-base-index 1
setw -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g bell-action none
setw -g monitor-activity off

set -s escape-time 0     # Address vim mode switching delay
set -g display-time 5000 # Display messages for 5s

# increase prefix + q duration
set -g display-panes-time 10000

# scripts dir
set -g @scripts "$DOTFILES/tmux/scripts"


# --- mouse --------------------------------------------------------------------

# To copy, left click and drag to highlight text, once you releaselef left click
# highlighted text will disappear and will be available in clibboard

set -g mouse on

bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M"\
    "if -Ft= '#{pane_in_mode}'\
    'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"

bind -n WheelDownPane select-pane -t= \; send-keys -M
bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
bind -T copy-mode-vi    C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-vi    C-WheelDownPane send-keys -X halfpage-down
bind -T copy-mode-emacs C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-emacs C-WheelDownPane send-keys -X halfpage-down


# --- actions ------------------------------------------------------------------

# toggle statusbar
bind Space set status

# reload config
bind , source-file ~/.config/tmux/tmux.conf \; display-message "Config Reloaded"

