# ------------------------------------------------------------------------------
# --# GHOSTNET MODE #----------------------------------------------------------

# use <ctrl+space>+g as trigger for ghostnet actions
bind g switch-client -T ghost

# always create ghostnet session
run-shell -b '
    tmux has-session -t ghostnet 2>/dev/null ||
    tmux new-session -d -s ghostnet
'

#-------------------------------------------------------------------------------

# connect to ghostnet over overlay
bind ` display-popup -w 60% -h 55% -E "tmux new-session -A -s ghostnet"

# move focused pane to ghostnet session
bind -T ghost b run-shell "#{@scripts}/ghostnet.sh back"

# move focused ghostnet window to a new window in current session
bind -T ghost n run-shell "#{@scripts}/ghostnet.sh upn"

# move focused ghostnet window to current window as vertical pane
bind -T ghost v run-shell "#{@scripts}/ghostnet.sh upd"

# move focused ghostnet window to current window as horizontal pane
bind -T ghost h run-shell "#{@scripts}/ghostnet.sh upl"

# close focused ghostnet window
bind -T ghost x run-shell "#{@scripts}/ghostnet.sh kill"

# --- navigation ---------------------------------------------------------------
# switch windows in ghostnet without bringing it to focus

bind -T ghost 1 select-window -t ghostnet:1
bind -T ghost 2 select-window -t ghostnet:2
bind -T ghost 3 select-window -t ghostnet:3
bind -T ghost 4 select-window -t ghostnet:4
bind -T ghost 5 select-window -t ghostnet:5
bind -T ghost 6 select-window -t ghostnet:6
bind -T ghost 7 select-window -t ghostnet:7
bind -T ghost 8 select-window -t ghostnet:8


# --- hacks - todo file --------------------------------------------------------

# focus/create todo window
bind -T ghost T run-shell "#{@scripts}/hacks_todo.sh switch"

# add new entry to todo
bind -T ghost t run-shell "#{@scripts}/hacks_todo.sh add"

