# ------------------------------------------------------------------------------
# --# GHOSTNET MODE #----------------------------------------------------------

# connect to ghostnet over overlay
bind ` display-popup -w 60% -h 55% -E "tmux new-session -A -s ghostnet"

unbind E
bind-key E run-shell '
if ! tmux has-session -t ghostnet 2>/dev/null; then
    tmux new-session -d -s ghostnet
    tmux set-option -t ghostnet @todo_prev "#{session_name}:#{window_index}"
    tmux new-window -t ghostnet -n todo "tail -f ~/.local/state/todo"
fi
tmux switch-client -t ghostnet
'

# move to background session
bind / if-shell 'tmux has-session -t ghostnet 2>/dev/null' '' 'new-session -d -s ghostnet' \; \
    break-pane -d -t ghostnet: \; \
    select-window -t ghostnet:$ \; \
    rename-window '#(date "+%d/%m %H:%M")'


# --- hacks - todo file --------------------------------------------------------

unbind e
bind e display-popup -E -w 40% -h 50% "#{@scripts}/hacks_todo.sh"

