# ------------------------------------------------------------------------------
# --# LAYOUTS #-----------------------------------------------------------------

# --- colours ------------------------------------------------------------------

# use xterm colors
set -g default-terminal "xterm-256color"

# copy mode
setw -g mode-style 'fg=#ff5f87 bg=#1c1c1c'

# messages
set -g message-style 'fg=#ff0000 bold'

# clock mode
setw -g clock-mode-colour colour1

# --- panel --------------------------------------------------------------------

# borders
set -g pane-border-style 'fg=#554040'
set -g pane-active-border-style 'fg=#f7768e'

## bar options
set-option -g status-style bg=default
set -g status-position top
set -g status-justify left
set -g status-left ''
set -g status-right-length 50
set -g status-left-length 50

# window status for the current and other windows
setw -g window-status-current-style 'fg=#000000 bg=#ff5f87'
setw -g window-status-current-format ' #I #[fg=#ff5f87,bg=#101020] #W '
setw -g window-status-style 'fg=#ff5f87 bg=#1c1c1c'
setw -g window-status-format ' #I #[fg=#875f5f,bg=#220000] #W '
setw -g window-status-bell-style 'fg=color2 bold'

# no need for right hand side panel
set -g status-right "#[fg=#ff5f87]#[fg=#000000 bg=#ff5f87] #S "

