# ------------------------------------------------------------------------------
# --# PLUGINS #-----------------------------------------------------------------

# prefix + I        refresh plugins
# prefix + u        update plugins
# prefix + alt + u  remove unused plugins

# --- plugin manager -----------------------------------------------------------

# config tpm path
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'

# list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'


# --- configs ------------------------------------------------------------------

# save sessions across reboots
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

# initialise tmux plugin manager
run '~/.config/tmux/plugins/tpm/tpm'

