# ------------------------------------------------------------------------------
# --# SESSIONS #----------------------------------------------------------------

# --- session management -------------------------------------------------------

# rename session
bind R command-prompt "rename-session '%%'"
bind r command-prompt "rename-window  '%%'"

# New window
unbind c
bind c new-window -c "#{pane_current_path}" "zsh"

# make new session from within existing session
unbind 0
bind 0 run-shell 'tmux switch-client -t \
    "$(TMUX= tmux -S "${TMUX%,*,*}" new-session -dP "$@")"'


# --- navigation ---------------------------------------------------------------

# open new panes in current dir
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"
bind > swap-pane -D  # swap current pane with the next one
bind < swap-pane -U  # swap current pane with the previous one

# Use ALT-<num> to switch windows
bind -n M-1 selectw -t 1
bind -n M-2 selectw -t 2
bind -n M-3 selectw -t 3
bind -n M-4 selectw -t 4
bind -n M-5 selectw -t 5
bind -n M-6 selectw -t 6
bind -n M-7 selectw -t 7
bind -n M-8 selectw -t 8

# Use fzf to switch sessions
bind -n M-\` run-shell "#{@scripts}/session_switch.sh"

